import { Timestamp } from '@angular/fire/firestore';

export interface Reply {
  id?: string; // generated by array index or uuid in real app, here we might just use index
  authorId: string;
  authorName: string;
  authorAvatar?: string;
  text: string;
  createdAt: Timestamp;
  likes: number;
  replyToName?: string;
}

export interface Comment {
  id?: string;
  postId: string;
  authorId: string;
  authorName?: string;
  text: string;
  rating: number; // 1-5 star rating
  createdAt: Timestamp;
  likes?: number;
  replies?: Reply[];
}
